import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, inject, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { forkJoin, finalize } from 'rxjs';
import { ApiService } from '../../core/services/api.service';
import { AppIconComponent } from '../../shared/components/app-icon/app-icon';
interface LeaveType{leaveTypeId:number;name:string;description?:string|null;isActive:boolean;}interface LeaveRequest{leaveRequestId:number;leaveTypeId:number;leaveTypeName:string;startDate:string;endDate:string;reason:string;status:string;createdAt:string;approvals?:{status:string;remarks?:string|null;approvedAt:string}[];}
@Component({selector:'app-student-leave',standalone:true,imports:[CommonModule,FormsModule,AppIconComponent],templateUrl:'./student-leave.html'})
export class StudentLeaveComponent implements OnInit{private readonly api=inject(ApiService);private readonly cdr=inject(ChangeDetectorRef);types:LeaveType[]=[];requests:LeaveRequest[]=[];activeView:'request'|'history'='request';leaveTypeId?:number;startDate='';endDate='';reason='';loading=true;actionLoading=false;error='';success='';ngOnInit():void{this.load();}load():void{this.loading=true;forkJoin({types:this.api.get<LeaveType[]>('Leave/types'),requests:this.api.get<LeaveRequest[]>('Leave/requests/my')}).pipe(finalize(()=>{this.loading=false;this.cdr.markForCheck();})).subscribe({next:r=>{this.types=r.types.filter(t=>t.isActive);this.requests=r.requests;},error:e=>this.error=this.readError(e,'Unable to load leave information.')});}submit():void{if(!this.leaveTypeId||!this.startDate||!this.endDate||!this.reason.trim()){this.error='Choose a leave type, dates and add the reason.';return;}if(new Date(this.endDate)<new Date(this.startDate)){this.error='End date cannot be before start date.';return;}this.actionLoading=true;this.error='';this.api.post<LeaveRequest>('Leave/requests',{leaveTypeId:this.leaveTypeId,startDate:this.startDate,endDate:this.endDate,reason:this.reason.trim()}).pipe(finalize(()=>{this.actionLoading=false;this.cdr.markForCheck();})).subscribe({next:r=>{this.requests=[r,...this.requests];this.success='Leave request submitted. You will be notified when its status changes.';this.leaveTypeId=undefined;this.startDate='';this.endDate='';this.reason='';this.activeView='history';},error:e=>this.error=this.readError(e,'Unable to submit leave request.')});}formatDate(v:string):string{return new Date(v).toLocaleDateString([], {dateStyle:'medium'});}private readError(e:any,f:string):string{return e?.error?.message??(typeof e?.error==='string'?e.error:f);}}
