import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, inject, OnInit } from '@angular/core';
import { forkJoin, finalize } from 'rxjs';
import { ApiService } from '../../core/services/api.service';
import { AppIconComponent } from '../../shared/components/app-icon/app-icon';
interface SportsEvent{sportsEventId:number;eventName:string;description?:string|null;eventDate:string;startTime:string;endTime:string;location?:string|null;isActive:boolean;}interface Registration{sportsRegistrationId:number;sportsEventId:number;status:number|string;registeredAt:string;}interface Meeting{coachMeetingId:number;sportsEventId:number;meetingDate:string;meetingTime:string;location?:string|null;notes?:string|null;}interface Limit{sportsEventDepartmentLimitId:number;departmentId:number;registrationLimit:number;}
@Component({selector:'app-student-sports',standalone:true,imports:[CommonModule,AppIconComponent],templateUrl:'./student-sports.html'})
export class StudentSportsComponent implements OnInit{private readonly api=inject(ApiService);private readonly cdr=inject(ChangeDetectorRef);events:SportsEvent[]=[];registrations:Registration[]=[];meetings:Meeting[]=[];limits:Limit[]=[];selected?:SportsEvent;activeView:'events'|'registrations'='events';loading=true;detailLoading=false;actionLoading=false;error='';success='';ngOnInit():void{this.load();}load():void{this.loading=true;forkJoin({events:this.api.get<SportsEvent[]>('SportsEvent/available'),registrations:this.api.get<Registration[]>('SportsRegistration/my')}).pipe(finalize(()=>{this.loading=false;this.cdr.markForCheck();})).subscribe({next:r=>{this.events=r.events;this.registrations=r.registrations;},error:e=>this.error=this.readError(e,'Unable to load sports events.')});}
openEvent(e:SportsEvent):void{this.selected=e;this.meetings=[];this.limits=[];this.detailLoading=true;const limitReq=this.api.get<Limit[]>(`SportsEventDepartmentLimit/event/${e.sportsEventId}`);if(this.hasActive(e.sportsEventId)){forkJoin({limits:limitReq,meetings:this.api.get<Meeting[]>(`CoachMeeting/my/event/${e.sportsEventId}`)}).pipe(finalize(()=>{this.detailLoading=false;this.cdr.markForCheck();})).subscribe({next:r=>{this.limits=r.limits;this.meetings=r.meetings;},error:x=>{this.error=this.readError(x,'Unable to load event details.');}});}else{limitReq.pipe(finalize(()=>{this.detailLoading=false;this.cdr.markForCheck();})).subscribe({next:l=>this.limits=l,error:()=>this.limits=[]});}}
register(e:SportsEvent):void{this.actionLoading=true;this.error='';this.api.post<Registration>('SportsRegistration',{sportsEventId:e.sportsEventId}).pipe(finalize(()=>{this.actionLoading=false;this.cdr.markForCheck();})).subscribe({next:r=>{this.registrations=[r,...this.registrations];this.success='Sports registration completed. Coach meeting updates will appear here and in Notifications.';this.openEvent(e);},error:x=>this.error=this.readError(x,'Unable to register for this sports event.')});}cancel(r:Registration):void{if(!confirm('Cancel this sports registration?'))return;this.actionLoading=true;this.api.patch<Registration>(`SportsRegistration/my/${r.sportsRegistrationId}/cancel`,{}).pipe(finalize(()=>{this.actionLoading=false;this.cdr.markForCheck();})).subscribe({next:u=>{this.registrations=this.registrations.map(x=>x.sportsRegistrationId===u.sportsRegistrationId?u:x);this.success='Sports registration cancelled.';if(this.selected?.sportsEventId===u.sportsEventId){this.meetings=[];}},error:e=>this.error=this.readError(e,'Unable to cancel registration.')});}hasActive(id:number):boolean{return this.registrations.some(r=>r.sportsEventId===id&&Number(r.status)!==2);}eventFor(r:Registration):SportsEvent|undefined{return this.events.find(e=>e.sportsEventId===r.sportsEventId);}status(v:number|string):string{if(typeof v==='string'&&isNaN(Number(v)))return v;return({0:'Registered',1:'Confirmed',2:'Cancelled'} as Record<number,string>)[Number(v)]??String(v);}isCancelled(r:Registration):boolean{return Number(r.status)===2;}formatDate(v:string):string{return new Date(v).toLocaleDateString([], {day:'2-digit',month:'short',year:'numeric'});}time(v:string):string{const[h,m]=v.slice(0,5).split(':').map(Number);const d=new Date();d.setHours(h||0,m||0);return d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});}private readError(e:any,f:string):string{return e?.error?.message??(typeof e?.error==='string'?e.error:f);}}
