import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, inject, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { forkJoin, finalize } from 'rxjs';
import { ApiService } from '../../core/services/api.service';
import { AppIconComponent } from '../../shared/components/app-icon/app-icon';
interface FeeType{feeTypeId:number;name:string;description:string;amount:number;isActive:boolean;}interface StudentFee{studentFeeId:number;feeTypeId:number;amount:number;dueDate?:string|null;status:string;examReference?:string|null;createdAt:string;}interface Payment{feePaymentId:number;studentFeeId:number;amount:number;paymentStatus:string;paymentReference?:string|null;paidAt?:string|null;}interface Refund{refundRequestId:number;paymentId:number;reason:string;amount:number;status:string;requestedAt:string;processedAt?:string|null;}
@Component({selector:'app-student-fees',standalone:true,imports:[CommonModule,FormsModule,AppIconComponent],templateUrl:'./student-fees.html'})
export class StudentFeesComponent implements OnInit{
 private readonly api=inject(ApiService);private readonly cdr=inject(ChangeDetectorRef);types:FeeType[]=[];fees:StudentFee[]=[];payments:Payment[]=[];refunds:Refund[]=[];activeView:'fees'|'payments'|'refunds'='fees';loading=true;actionLoading=false;error='';success='';refundModal=false;refundPayment?:Payment;refundReason='';
 ngOnInit():void{this.load();}load():void{this.loading=true;forkJoin({types:this.api.get<FeeType[]>('Fees/types'),fees:this.api.get<StudentFee[]>('Fees/my'),payments:this.api.get<Payment[]>('Fees/my/payments'),refunds:this.api.get<Refund[]>('Fees/my/refunds')}).pipe(finalize(()=>{this.loading=false;this.cdr.markForCheck();})).subscribe({next:r=>{this.types=r.types;this.fees=r.fees;this.payments=r.payments;this.refunds=r.refunds;},error:e=>this.error=this.readError(e,'Unable to load fee information.')});}
 pay(fee:StudentFee):void{if(!confirm(`Pay Rs. ${fee.amount} for ${this.typeName(fee.feeTypeId)}?`))return;this.actionLoading=true;this.error='';this.api.post<Payment>(`Fees/my/${fee.studentFeeId}/pay`,{paymentReference:`SIM-FEE-${fee.studentFeeId}-${Date.now()}`}).pipe(finalize(()=>{this.actionLoading=false;this.cdr.markForCheck();})).subscribe({next:p=>{this.payments=[p,...this.payments];this.fees=this.fees.map(f=>f.studentFeeId===fee.studentFeeId?{...f,status:'Paid'}:f);this.success='Payment completed. Your receipt is available in payment history.';},error:e=>this.error=this.readError(e,'Unable to complete payment.')});}
 openRefund(p:Payment):void{this.refundPayment=p;this.refundReason='';this.refundModal=true;}
 requestRefund():void{if(!this.refundPayment||!this.refundReason.trim()){this.error='Tell us why you are requesting a refund.';return;}this.actionLoading=true;this.api.post<Refund>(`Fees/my/payments/${this.refundPayment.feePaymentId}/refund`,{reason:this.refundReason.trim()}).pipe(finalize(()=>{this.actionLoading=false;this.cdr.markForCheck();})).subscribe({next:r=>{this.refunds=[r,...this.refunds];this.refundModal=false;this.activeView='refunds';this.success='Refund request submitted.';},error:e=>this.error=this.readError(e,'Unable to request refund.')});}
 typeName(id:number):string{return this.types.find(t=>t.feeTypeId===id)?.name??'University fee';}typeDescription(id:number):string{return this.types.find(t=>t.feeTypeId===id)?.description??'';}isPaid(f:StudentFee):boolean{return f.status?.toLowerCase()==='paid';}formatDate(v?:string|null):string{return v?new Date(v).toLocaleDateString([], {day:'2-digit',month:'short',year:'numeric'}):'No due date';}feeNameForPayment(payment:Payment):string{const fee=this.fees.find(x=>x.studentFeeId===payment.studentFeeId);return fee?this.typeName(fee.feeTypeId):'Fee payment';}hasRefund(p:Payment):boolean{return this.refunds.some(r=>r.paymentId===p.feePaymentId && !['Rejected','Processed'].includes(r.status));}private readError(e:any,f:string):string{return e?.error?.message??(typeof e?.error==='string'?e.error:f);}
}
