import { CommonModule } from '@angular/common';
import { HttpParams } from '@angular/common/http';
import { ChangeDetectorRef, Component, inject, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { forkJoin, finalize } from 'rxjs';
import { ApiService } from '../../core/services/api.service';
import { AppIconComponent } from '../../shared/components/app-icon/app-icon';
interface Gym{gymId:number;name:string;location:string;capacity:number;description:string;isActive:boolean;}interface Slot{slotId:number;gymId:number;gymName:string;slotDate:string;startTime:string;endTime:string;remainingCapacity:number;isAvailable:boolean;requiresPayment:boolean;feeAmount:number;}interface Availability{gymId:number;gymName:string;date:string;slots:Slot[];}interface Booking{bookingId:number;slotId:number;gymId:number;gymName:string;bookingDate:string;startTime:string;endTime:string;status:string;requiresPayment:boolean;feeAmount:number;paymentStatus:string;expiresAt?:string|null;}
@Component({selector:'app-student-gym',standalone:true,imports:[CommonModule,FormsModule,AppIconComponent],templateUrl:'./student-gym.html'})
export class StudentGymComponent implements OnInit{private readonly api=inject(ApiService);private readonly cdr=inject(ChangeDetectorRef);gyms:Gym[]=[];bookings:Booking[]=[];selectedGym?:Gym;date=new Date(Date.now()+86400000).toISOString().slice(0,10);slots:Slot[]=[];activeView:'gyms'|'bookings'='gyms';loading=true;actionLoading=false;error='';success='';ngOnInit():void{this.load();}load():void{this.loading=true;forkJoin({gyms:this.api.get<Gym[]>('Gym'),bookings:this.api.get<Booking[]>('Gym/bookings/my')}).pipe(finalize(()=>{this.loading=false;this.cdr.markForCheck();})).subscribe({next:r=>{this.gyms=r.gyms.filter(g=>g.isActive);this.bookings=r.bookings;},error:e=>this.error=this.readError(e,'Unable to load gym services.')});}openGym(g:Gym):void{this.selectedGym=g;this.slots=[];this.checkAvailability();}checkAvailability():void{if(!this.selectedGym)return;this.actionLoading=true;const params=new HttpParams().set('date',this.date);this.api.get<Availability>(`Gym/${this.selectedGym.gymId}/availability`,params).pipe(finalize(()=>{this.actionLoading=false;this.cdr.markForCheck();})).subscribe({next:a=>this.slots=a.slots,error:e=>this.error=this.readError(e,'Unable to load gym slots.')});}book(slot:Slot):void{this.actionLoading=true;this.api.post<Booking>('Gym/bookings',{slotId:slot.slotId}).pipe(finalize(()=>{this.actionLoading=false;this.cdr.markForCheck();})).subscribe({next:b=>{this.bookings=[b,...this.bookings];if(b.requiresPayment&&b.paymentStatus?.toLowerCase()!=='paid'){this.pay(b);}else this.success='Gym booking confirmed.';},error:e=>this.error=this.readError(e,'Unable to book this gym slot.')});}pay(b:Booking):void{this.actionLoading=true;this.api.post<Booking>(`Gym/bookings/${b.bookingId}/pay`,{paymentReference:`SIM-GYM-${b.bookingId}-${Date.now()}`}).pipe(finalize(()=>{this.actionLoading=false;this.cdr.markForCheck();})).subscribe({next:u=>{this.bookings=this.bookings.map(x=>x.bookingId===u.bookingId?u:x);this.success='Gym booking paid and confirmed.';},error:e=>this.error=this.readError(e,'Unable to complete gym payment.')});}cancel(b:Booking):void{if(!confirm('Cancel this gym booking?'))return;this.actionLoading=true;this.api.delete<Booking>(`Gym/bookings/${b.bookingId}`).pipe(finalize(()=>{this.actionLoading=false;this.cdr.markForCheck();})).subscribe({next:u=>{this.bookings=this.bookings.map(x=>x.bookingId===u.bookingId?u:x);this.success='Gym booking cancelled.';},error:e=>this.error=this.readError(e,'Unable to cancel gym booking.')});}time(v:string):string{const [h,m]=v.slice(0,5).split(':').map(Number);const d=new Date();d.setHours(h||0,m||0);return d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});}formatDate(v:string):string{return new Date(v).toLocaleDateString([], {dateStyle:'medium'});}private readError(e:any,f:string):string{return e?.error?.message??(typeof e?.error==='string'?e.error:f);}}
