import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, inject, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { forkJoin, finalize } from 'rxjs';
import { ApiService } from '../../core/services/api.service';
import { AppIconComponent } from '../../shared/components/app-icon/app-icon';
interface Category{complaintCategoryId:number;name:string;description:string;isActive:boolean;} interface Complaint{complaintId:number;categoryId:number;title:string;description:string;status:string;createdAt:string;updatedAt?:string|null;} interface History{status:string;remarks?:string|null;changedAt?:string|null;}
@Component({selector:'app-student-complaints',standalone:true,imports:[CommonModule,FormsModule,AppIconComponent],templateUrl:'./student-complaints.html'})
export class StudentComplaintsComponent implements OnInit{
 private readonly api=inject(ApiService);private readonly cdr=inject(ChangeDetectorRef);categories:Category[]=[];complaints:Complaint[]=[];selectedComplaint?:Complaint;history:History[]=[];activeView:'submit'|'history'='submit';categoryId?:number;title='';description='';loading=true;actionLoading=false;error='';success='';resolutionModal=false;resolutionRemarks='';
 ngOnInit():void{this.load();} load():void{this.loading=true;forkJoin({categories:this.api.get<Category[]>('Complaints/categories'),complaints:this.api.get<Complaint[]>('Complaints/my')}).pipe(finalize(()=>{this.loading=false;this.cdr.markForCheck();})).subscribe({next:r=>{this.categories=r.categories.filter(c=>c.isActive);this.complaints=r.complaints;},error:e=>this.error=this.readError(e,'Unable to load complaints.')});}
 submit():void{if(!this.categoryId||!this.title.trim()||!this.description.trim()){this.error='Choose a category and complete the title and description.';return;}this.actionLoading=true;this.error='';this.api.post<Complaint>('Complaints',{categoryId:this.categoryId,title:this.title.trim(),description:this.description.trim()}).pipe(finalize(()=>{this.actionLoading=false;this.cdr.markForCheck();})).subscribe({next:c=>{this.complaints=[c,...this.complaints];this.success='Complaint submitted. You can track status updates here and in Notifications.';this.categoryId=undefined;this.title='';this.description='';this.activeView='history';},error:e=>this.error=this.readError(e,'Unable to submit the complaint.')});}
 openComplaint(c:Complaint):void{this.selectedComplaint=c;this.actionLoading=true;this.api.get<History[]>(`Complaints/my/${c.complaintId}/history`).pipe(finalize(()=>{this.actionLoading=false;this.cdr.markForCheck();})).subscribe({next:h=>this.history=h,error:e=>this.error=this.readError(e,'Unable to load complaint history.')});}

 confirmResolution():void{if(!this.selectedComplaint)return;this.actionLoading=true;this.error='';this.api.post<Complaint>(`Complaints/${this.selectedComplaint.complaintId}/confirm-resolution`,{remarks:this.resolutionRemarks.trim()}).pipe(finalize(()=>{this.actionLoading=false;this.cdr.markForCheck();})).subscribe({next:c=>{this.selectedComplaint=c;this.complaints=this.complaints.map(x=>x.complaintId===c.complaintId?c:x);this.resolutionModal=false;this.resolutionRemarks='';this.success='Resolution confirmed and complaint closed.';this.openComplaint(c);},error:e=>this.error=this.readError(e,'Unable to confirm the resolution.')});}
 categoryName(id:number):string{return this.categories.find(c=>c.complaintCategoryId===id)?.name??'Complaint';}formatDate(v?:string|null):string{return v?new Date(v).toLocaleString([], {dateStyle:'medium',timeStyle:'short'}):'';}private readError(e:any,f:string):string{return e?.error?.message??(typeof e?.error==='string'?e.error:f);}
}
