import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { finalize, forkJoin } from 'rxjs';
import { ApiService } from '../../../core/services/api.service';
import { AppIconComponent } from '../../../shared/components/app-icon/app-icon';
interface SportsEvent{sportsEventId:number;eventName:string;description?:string|null;eventDate:string;startTime:string;endTime:string;location?:string|null;isActive:boolean;}
interface Registration{sportsRegistrationId:number;sportsEventId:number;studentId:number;status:number|string;registeredAt:string;}
interface Meeting{coachMeetingId:number;sportsEventId:number;meetingDate:string;meetingTime:string;location?:string|null;notes?:string|null;}
interface Limit{sportsEventDepartmentLimitId:number;sportsEventId:number;departmentId:number;registrationLimit:number;}
interface Student{studentId:number;masterStudentId:number;firstName:string;lastName:string;}
interface Master{masterStudentId:number;universityStudentId:string;}
interface Department{departmentId:number;departmentName:string;name?:string;}
@Component({selector:'app-admin-sports',standalone:true,imports:[CommonModule,FormsModule,AppIconComponent],templateUrl:'./admin-sports.html'})
export class AdminSportsComponent implements OnInit{
 private readonly api=inject(ApiService);private readonly cdr=inject(ChangeDetectorRef);
 events:SportsEvent[]=[];registrations:Registration[]=[];meetings:Meeting[]=[];limits:Limit[]=[];students:Student[]=[];masters:Master[]=[];departments:Department[]=[];
 selected?:SportsEvent;tab:'overview'|'registrations'|'meetings'|'limits'='overview';loading=true;detailLoading=false;saving=false;error='';success='';search='';eventModal=false;meetingModal=false;limitModal=false;editingEvent=false;editingMeeting?:Meeting;
 eventForm:any=this.emptyEvent();meetingForm:any={meetingDate:'',meetingTime:'16:00',location:'',notes:''};limitForm:any={departmentId:'',registrationLimit:10};
 ngOnInit():void{this.load();}
 load():void{this.loading=true;forkJoin({events:this.api.get<SportsEvent[]>('SportsEvent'),regs:this.api.get<Registration[]>('SportsRegistration'),meetings:this.api.get<Meeting[]>('CoachMeeting'),students:this.api.get<Student[]>('Student'),masters:this.api.get<Master[]>('StudentMasterList'),departments:this.api.get<Department[]>('AcademicMaster/departments')}).pipe(finalize(()=>{this.loading=false;this.cdr.markForCheck();})).subscribe({next:r=>{this.events=r.events;this.registrations=r.regs;this.meetings=r.meetings;this.students=r.students;this.masters=r.masters;this.departments=r.departments;},error:e=>this.error=this.readError(e,'Unable to load sports management.')});}
 get filtered():SportsEvent[]{const q=this.search.trim().toLowerCase();return this.events.filter(e=>!q||`${e.eventName} ${e.location??''} ${e.description??''}`.toLowerCase().includes(q));}
 openEvent(e:SportsEvent):void{this.selected=e;this.tab='overview';this.detailLoading=true;this.api.get<Limit[]>(`SportsEventDepartmentLimit/event/${e.sportsEventId}`).pipe(finalize(()=>{this.detailLoading=false;this.cdr.markForCheck();})).subscribe({next:l=>this.limits=l,error:x=>this.error=this.readError(x,'Unable to load department limits.')});}
 back():void{this.selected=undefined;this.limits=[];}
 get selectedRegistrations():Registration[]{return this.selected?this.registrations.filter(r=>r.sportsEventId===this.selected!.sportsEventId):[];}
 get selectedMeetings():Meeting[]{return this.selected?this.meetings.filter(m=>m.sportsEventId===this.selected!.sportsEventId).sort((a,b)=>new Date(a.meetingDate).getTime()-new Date(b.meetingDate).getTime()):[];}
 studentName(id:number):string{const s=this.students.find(x=>x.studentId===id);return s?`${s.firstName} ${s.lastName}`.trim():'Student';}
 studentNumber(id:number):string{const s=this.students.find(x=>x.studentId===id);return this.masters.find(m=>m.masterStudentId===s?.masterStudentId)?.universityStudentId??'';}
 status(v:number|string):string{if(typeof v==='string'&&isNaN(Number(v)))return v;return({0:'Registered',1:'Confirmed',2:'Cancelled'} as Record<number,string>)[Number(v)]??String(v);}
 setStatus(r:Registration,status:number):void{this.api.patch<Registration>(`SportsRegistration/${r.sportsRegistrationId}/status`,{status}).subscribe({next:u=>{this.registrations=this.registrations.map(x=>x.sportsRegistrationId===u.sportsRegistrationId?u:x);this.success=`${this.studentName(r.studentId)} registration marked ${this.status(status)}.`;this.cdr.markForCheck();},error:e=>this.error=this.readError(e,'Unable to update registration.')});}
 openCreateEvent():void{this.editingEvent=false;this.eventForm=this.emptyEvent();this.eventModal=true;}
 openEditEvent():void{if(!this.selected)return;this.editingEvent=true;this.eventForm={...this.selected,eventDate:this.selected.eventDate.slice(0,10),startTime:this.selected.startTime.slice(0,5),endTime:this.selected.endTime.slice(0,5)};this.eventModal=true;}
 saveEvent():void{if(!this.eventForm.eventName||!this.eventForm.eventDate)return;this.saving=true;const body={eventName:this.eventForm.eventName,description:this.eventForm.description||null,eventDate:this.eventForm.eventDate,startTime:this.eventForm.startTime,endTime:this.eventForm.endTime,location:this.eventForm.location||null,...(this.editingEvent?{isActive:!!this.eventForm.isActive}:{})};const req=this.editingEvent&&this.selected?this.api.put(`SportsEvent/${this.selected.sportsEventId}`,body):this.api.post<SportsEvent>('SportsEvent',body);req.pipe(finalize(()=>{this.saving=false;this.cdr.markForCheck();})).subscribe({next:()=>{this.eventModal=false;this.success=this.editingEvent?'Sports event updated.':'Sports event created.';this.load();},error:e=>this.error=this.readError(e,'Unable to save sports event.')});}
 openMeeting(m?:Meeting):void{this.editingMeeting=m;if(m)this.meetingForm={meetingDate:m.meetingDate.slice(0,10),meetingTime:m.meetingTime.slice(0,5),location:m.location??'',notes:m.notes??''};else this.meetingForm={meetingDate:'',meetingTime:'16:00',location:'',notes:''};this.meetingModal=true;}
 saveMeeting():void{if(!this.selected||!this.meetingForm.meetingDate||!this.meetingForm.meetingTime)return;this.saving=true;const body={sportsEventId:this.selected.sportsEventId,...this.meetingForm};const req=this.editingMeeting?this.api.put(`CoachMeeting/${this.editingMeeting.coachMeetingId}`,body):this.api.post<Meeting>('CoachMeeting',body);req.pipe(finalize(()=>{this.saving=false;this.cdr.markForCheck();})).subscribe({next:()=>{this.meetingModal=false;this.success=this.editingMeeting?'Coach meeting updated.':'Coach meeting scheduled. Registered students were notified automatically.';this.reloadMeetings();},error:e=>this.error=this.readError(e,'Unable to save coach meeting.')});}
 private reloadMeetings():void{this.api.get<Meeting[]>('CoachMeeting').subscribe({next:m=>{this.meetings=m;this.cdr.markForCheck();}});}
 saveLimit():void{if(!this.selected||!this.limitForm.departmentId)return;this.saving=true;this.api.post<Limit>('SportsEventDepartmentLimit',{sportsEventId:this.selected.sportsEventId,departmentId:Number(this.limitForm.departmentId),registrationLimit:Number(this.limitForm.registrationLimit)}).pipe(finalize(()=>{this.saving=false;this.cdr.markForCheck();})).subscribe({next:l=>{this.limits=[...this.limits,l];this.limitModal=false;this.limitForm={departmentId:'',registrationLimit:10};this.success='Department registration limit added.';},error:e=>this.error=this.readError(e,'Unable to save department limit.')});}
 departmentName(id:number):string{const d=this.departments.find(x=>x.departmentId===id);return d?.departmentName??d?.name??'Department';}
 date(v:string):string{return new Date(v).toLocaleDateString([], {day:'2-digit',month:'short',year:'numeric'});} time(v:string):string{const [h,m]=v.slice(0,5).split(':').map(Number);const d=new Date();d.setHours(h||0,m||0);return d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});} confirmedCount():number{return this.selectedRegistrations.filter(r=>Number(r.status)===1).length;}
 private emptyEvent(){return{eventName:'',description:'',eventDate:'',startTime:'09:00',endTime:'11:00',location:'',isActive:true};} private readError(e:any,f:string):string{return e?.error?.message??(typeof e?.error==='string'?e.error:f);}
}
