import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { finalize, forkJoin } from 'rxjs';
import { ApiService } from '../../../core/services/api.service';
import { AppIconComponent } from '../../../shared/components/app-icon/app-icon';
interface Canteen{canteenId:number;hostelId:number;canteenName:string;description?:string|null;isActive:boolean;}
interface Hostel{hostelId:number;hostelName:string;}
interface Package{mealPackageId:number;canteenId?:number|null;canteenName:string;packageCode:string;packageName:string;planType:string;billingPeriod:string;breakfastIncluded:boolean;lunchIncluded:boolean;dinnerIncluded:boolean;price:number;isActive:boolean;}
interface Menu{menuItemId:number;canteenId:number;itemName:string;description?:string|null;mealType:number|string;price:number;isAvailable:boolean;}
interface Student{studentId:number;masterStudentId:number;firstName:string;lastName:string;}
interface Master{masterStudentId:number;universityStudentId:string;}
interface Subscription{mealSubscriptionId:number;studentId:number;canteenId?:number|null;canteenName:string;packageName:string;planType:string;billingPeriod:string;startDate:string;endDate:string;amount:number;status:number|string;paymentStatus:string;}
@Component({selector:'app-admin-canteen',standalone:true,imports:[CommonModule,FormsModule,AppIconComponent],templateUrl:'./admin-canteen.html'})
export class AdminCanteenComponent implements OnInit{
 private readonly api=inject(ApiService);private readonly cdr=inject(ChangeDetectorRef);
 canteens:Canteen[]=[];hostels:Hostel[]=[];packages:Package[]=[];students:Student[]=[];masters:Master[]=[];selected?:Canteen;menu:Menu[]=[];subscriptions:Subscription[]=[];tab:'overview'|'menu'|'packages'|'subscriptions'|'collection'='overview';loading=true;detailLoading=false;saving=false;error='';success='';search='';selectedStudentId?:number;selectedSubscription?:Subscription;canteenModal=false;menuModal=false;packageModal=false;
 canteenForm:any={hostelId:'',canteenName:'',description:''};menuForm:any={itemName:'',description:'',mealType:1,price:0};packageForm:any={planType:'FB',billingPeriod:'Monthly',price:0};collectionForm:any={mealDate:new Date().toISOString().slice(0,10),mealType:1};
 ngOnInit():void{this.load();}
 load():void{this.loading=true;forkJoin({canteens:this.api.get<Canteen[]>('canteen/canteens'),hostels:this.api.get<Hostel[]>('Hostel'),packages:this.api.get<Package[]>('canteen/packages'),students:this.api.get<Student[]>('Student'),masters:this.api.get<Master[]>('StudentMasterList')}).pipe(finalize(()=>{this.loading=false;this.cdr.markForCheck();})).subscribe({next:r=>{this.canteens=r.canteens;this.hostels=r.hostels;this.packages=r.packages;this.students=r.students;this.masters=r.masters;},error:e=>this.error=this.readError(e,'Unable to load canteen management.')});}
 get filtered():Canteen[]{const q=this.search.trim().toLowerCase();return this.canteens.filter(c=>!q||`${c.canteenName} ${c.description??''}`.toLowerCase().includes(q));}
 openCanteen(c:Canteen):void{this.selected=c;this.tab='overview';this.menu=[];this.subscriptions=[];this.selectedStudentId=undefined;this.selectedSubscription=undefined;this.loadMenu();}
 back():void{this.selected=undefined;}
 loadMenu():void{if(!this.selected)return;this.detailLoading=true;this.api.get<Menu[]>(`canteen/canteens/${this.selected.canteenId}/menu`).pipe(finalize(()=>{this.detailLoading=false;this.cdr.markForCheck();})).subscribe({next:m=>this.menu=m,error:e=>this.error=this.readError(e,'Unable to load canteen menu.')});}
 get selectedPackages():Package[]{return this.selected?this.packages.filter(p=>p.canteenId===this.selected!.canteenId):[];}
 loadStudentSubscriptions():void{if(!this.selectedStudentId){this.subscriptions=[];return;}this.detailLoading=true;this.api.get<Subscription[]>(`canteen/students/${this.selectedStudentId}/subscriptions`).pipe(finalize(()=>{this.detailLoading=false;this.cdr.markForCheck();})).subscribe({next:s=>this.subscriptions=s.filter(x=>!this.selected||!x.canteenId||x.canteenId===this.selected.canteenId),error:e=>this.error=this.readError(e,'Unable to load student subscriptions.')});}
 createCanteen():void{if(!this.canteenForm.hostelId||!this.canteenForm.canteenName)return;this.saving=true;this.api.post<Canteen>('canteen/canteens',{...this.canteenForm,hostelId:Number(this.canteenForm.hostelId)}).pipe(finalize(()=>{this.saving=false;this.cdr.markForCheck();})).subscribe({next:c=>{this.canteens=[...this.canteens,c];this.canteenModal=false;this.canteenForm={hostelId:'',canteenName:'',description:''};this.success='Canteen created.';},error:e=>this.error=this.readError(e,'Unable to create canteen.')});}
 addMenu():void{if(!this.selected||!this.menuForm.itemName)return;this.saving=true;this.api.post<Menu>('canteen/menu',{canteenId:this.selected.canteenId,itemName:this.menuForm.itemName,description:this.menuForm.description||null,mealType:Number(this.menuForm.mealType),price:Number(this.menuForm.price)}).pipe(finalize(()=>{this.saving=false;this.cdr.markForCheck();})).subscribe({next:m=>{this.menu=[...this.menu,m];this.menuModal=false;this.menuForm={itemName:'',description:'',mealType:1,price:0};this.success='Menu item added.';},error:e=>this.error=this.readError(e,'Unable to add menu item.')});}
 addPackage():void{if(!this.selected)return;this.saving=true;this.api.post<Package>('canteen/packages',{canteenId:this.selected.canteenId,planType:this.packageForm.planType,billingPeriod:this.packageForm.billingPeriod,price:Number(this.packageForm.price)}).pipe(finalize(()=>{this.saving=false;this.cdr.markForCheck();})).subscribe({next:p=>{this.packages=[...this.packages,p];this.packageModal=false;this.packageForm={planType:'FB',billingPeriod:'Monthly',price:0};this.success='Meal package created.';},error:e=>this.error=this.readError(e,'Unable to create meal package.')});}
 collect():void{if(!this.selectedSubscription)return;const q=`canteen/usage/collect?mealSubscriptionId=${this.selectedSubscription.mealSubscriptionId}&mealDate=${encodeURIComponent(this.collectionForm.mealDate)}&mealType=${this.collectionForm.mealType}`;this.saving=true;this.api.put<any>(q,{}).pipe(finalize(()=>{this.saving=false;this.cdr.markForCheck();})).subscribe({next:()=>this.success='Meal collection recorded.',error:e=>this.error=this.readError(e,'Unable to record meal collection.')});}
 hostelName(id:number):string{return this.hostels.find(h=>h.hostelId===id)?.hostelName??'Hostel';} studentLabel(s:Student):string{const m=this.masters.find(x=>x.masterStudentId===s.masterStudentId);return `${s.firstName} ${s.lastName}${m?.universityStudentId?' · '+m.universityStudentId:''}`.trim();}
 mealType(v:number|string):string{if(typeof v==='string'&&isNaN(Number(v)))return v;return({1:'Breakfast',2:'Lunch',3:'Dinner'} as Record<number,string>)[Number(v)]??'Meal';} planName(p:Package):string{if(p.planType==='FB')return'Full meal plan';if(p.planType==='HB')return'Breakfast + dinner plan';if(p.planType==='BB')return'Breakfast plan';return p.packageName||p.planType;} meals(p:Package):string{const m=[];if(p.breakfastIncluded)m.push('Breakfast');if(p.lunchIncluded)m.push('Lunch');if(p.dinnerIncluded)m.push('Dinner');return m.join(' + ');} status(v:number|string):string{if(typeof v==='string'&&isNaN(Number(v)))return v;return({1:'Pending',2:'Active',3:'Expired',4:'Cancelled'} as Record<number,string>)[Number(v)]??String(v);} date(v:string):string{return new Date(v).toLocaleDateString([], {day:'2-digit',month:'short',year:'numeric'});} private readError(e:any,f:string):string{return e?.error?.message??(typeof e?.error==='string'?e.error:f);}
}
